--    Librepos is a point of sales application designed for touch screens.
--    Copyright (C) 2005 Adrian Romero Corchado.
--    http://sourceforge.net/projects/librepos
--
--    This program is free software; you can redistribute it and/or modify
--    it under the terms of the GNU General Public License as published by
--    the Free Software Foundation; either version 2 of the License, or
--    (at your option) any later version.
--
--    This program is distributed in the hope that it will be useful,
--    but WITHOUT ANY WARRANTY; without even the implied warranty of
--    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--    GNU General Public License for more details.
--
--    You should have received a copy of the GNU General Public License
--    along with this program; if not, write to the Free Software
--    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-- Librepos Database upgrade script for MySQL from version 0.0.22 to 0.0.23
-- v0.0.23

UPDATE LIBREPOS SET VERSION = '0.0.23';

ALTER TABLE PEOPLE DROP CONSTRAINT PEOPLE_FK_1;

ALTER TABLE ROLES DROP PRIMARY KEY;
ALTER TABLE ROLES ADD COLUMN ID VARCHAR(255);
UPDATE ROLES SET ID=NAME;
ALTER TABLE ROLES MODIFY COLUMN ID VARCHAR(255) NOT NULL;
ALTER TABLE ROLES ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX ROLES_NAME_INX ON ROLES(NAME);

ALTER TABLE PEOPLE ADD CONSTRAINT PEOPLE_FK_1 FOREIGN KEY (ROLE) REFERENCES ROLES(ID);

UPDATE ROLES SET PERMISSIONS = $FILE{/net/adrianromero/templates/Role.Administrator.xml} WHERE NAME='Administrator';
UPDATE ROLES SET PERMISSIONS = $FILE{/net/adrianromero/templates/Role.Manager.xml} WHERE NAME='Manager';
UPDATE ROLES SET PERMISSIONS = $FILE{/net/adrianromero/templates/Role.Employee.xml} WHERE NAME='Employee';
UPDATE ROLES SET PERMISSIONS = $FILE{/net/adrianromero/templates/Role.Guest.xml} WHERE NAME='Guest';

ALTER TABLE TICKETS DROP CONSTRAINT TICKETS_FK_2;

ALTER TABLE PEOPLE DROP PRIMARY KEY;
ALTER TABLE PEOPLE ADD COLUMN ID VARCHAR(255);
UPDATE PEOPLE SET ID=NAME;
ALTER TABLE PEOPLE MODIFY COLUMN ID VARCHAR(255) NOT NULL;
ALTER TABLE PEOPLE ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX PEOPLE_NAME_INX ON PEOPLE(NAME);

ALTER TABLE TICKETS ADD CONSTRAINT TICKETS_FK_2 FOREIGN KEY (PERSON) REFERENCES PEOPLE(ID);

ALTER TABLE RESOURCES DROP PRIMARY KEY;
ALTER TABLE RESOURCES ADD COLUMN ID VARCHAR(255);
UPDATE RESOURCES SET ID=NAME;
ALTER TABLE RESOURCES MODIFY COLUMN ID VARCHAR(255) NOT NULL;
ALTER TABLE RESOURCES ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX RESOURCES_NAME_INX ON RESOURCES(NAME);

INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('0', 'Printer.Start', 0, $FILE{/net/adrianromero/templates/Printer.Start.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('1', 'Printer.Ticket', 0, $FILE{/net/adrianromero/templates/Printer.Ticket.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('2', 'Printer.Ticket2', 0, $FILE{/net/adrianromero/templates/Printer.Ticket2.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('3', 'Printer.TicketPreview', 0, $FILE{/net/adrianromero/templates/Printer.TicketPreview.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('4', 'Printer.TicketTotal', 0, $FILE{/net/adrianromero/templates/Printer.TicketTotal.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('5', 'Printer.OpenDrawer', 0, $FILE{/net/adrianromero/templates/Printer.OpenDrawer.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('6', 'Printer.Ticket.Logo', 1, $FILE{/net/adrianromero/templates/Printer.Ticket.Logo.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('7', 'Printer.TicketLine', 0, $FILE{/net/adrianromero/templates/Printer.TicketLine.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('8', 'Printer.CloseCash', 0, $FILE{/net/adrianromero/templates/Printer.CloseCash.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('9', 'Window.Logo', 1, $FILE{/net/adrianromero/templates/Window.Logo.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('10', 'Window.Title', 0, $FILE{/net/adrianromero/templates/Window.Title.txt});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('11', 'Ticket.Buttons', 0, $FILE{/net/adrianromero/templates/Ticket.Buttons.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('12', 'Ticket.Line', 0, $FILE{/net/adrianromero/templates/Ticket.Line.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('13', 'Printer.Inventory', 0, $FILE{/net/adrianromero/templates/Printer.Inventory.xml});

ALTER TABLE CATEGORIES MODIFY COLUMN ID VARCHAR(255) NOT NULL;

ALTER TABLE TAXES MODIFY COLUMN ID VARCHAR(255) NOT NULL;
CREATE UNIQUE INDEX TAXES_NAME_INX ON TAXES(NAME);

ALTER TABLE PRODUCTS MODIFY COLUMN CATEGORY VARCHAR(255) NOT NULL;
ALTER TABLE PRODUCTS MODIFY COLUMN TAX VARCHAR(255) NOT NULL;

ALTER TABLE LOCATIONS MODIFY COLUMN ID VARCHAR(255) NOT NULL;
CREATE UNIQUE INDEX LOCATIONS_NAME_INX ON LOCATIONS(NAME);

ALTER TABLE STOCKDIARY MODIFY COLUMN ID VARCHAR(255) NOT NULL;
ALTER TABLE STOCKDIARY MODIFY COLUMN LOCATION VARCHAR(255) NOT NULL;
DROP TABLE STOCKDIARYNUM;
ALTER TABLE STOCKCURRENT MODIFY COLUMN LOCATION VARCHAR(255) NOT NULL;

ALTER TABLE CLOSEDCASH MODIFY COLUMN MONEY VARCHAR(255) NOT NULL;
DROP TABLE CLOSEDCASHNUM;

ALTER TABLE TICKETS MODIFY COLUMN MONEY VARCHAR(255) NOT NULL;

ALTER TABLE PRODUCTSOUT MODIFY COLUMN TAXID VARCHAR(255);

ALTER TABLE PAYMENTS MODIFY COLUMN ID VARCHAR(255) NOT NULL;
DROP TABLE PAYMENTSNUM;

ALTER TABLE FLOORS MODIFY COLUMN ID VARCHAR(255) NOT NULL;
CREATE UNIQUE INDEX FLOORS_NAME_INX ON FLOORS(NAME);

ALTER TABLE PLACES MODIFY COLUMN FLOOR VARCHAR(255) NOT NULL;
ALTER TABLE PLACES ADD COLUMN ID VARCHAR(255);
UPDATE PLACES SET ID = NAME;
ALTER TABLE PLACES MODIFY COLUMN ID VARCHAR(255) NOT NULL;
ALTER TABLE PLACES DROP PRIMARY KEY;
ALTER TABLE PLACES ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX PLACES_NAME_INX ON PLACES(NAME);

ALTER TABLE RESERVATIONS MODIFY COLUMN ID VARCHAR(255) NOT NULL;
ALTER TABLE RESERVATIONS ADD COLUMN CREATED DATETIME DEFAULT '2001-01-01 00:00:00' NOT NULL;
DROP TABLE RESERVATIONSNUM;

CREATE UNIQUE INDEX THIRDPARTIES_CIF_INX ON THIRDPARTIES(CIF);
CREATE UNIQUE INDEX THIRDPARTIES_NAME_INX ON THIRDPARTIES(NAME);

CREATE TABLE SHAREDTICKETS (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CONTENT MEDIUMBLOB,
    PRIMARY KEY(ID)
);

