--    Librepos is a point of sales application designed for touch screens.
--    Copyright (C) 2005 Adrian Romero Corchado.
--    http://sourceforge.net/projects/librepos
--
--    This program is free software; you can redistribute it and/or modify
--    it under the terms of the GNU General Public License as published by
--    the Free Software Foundation; either version 2 of the License, or
--    (at your option) any later version.
--
--    This program is distributed in the hope that it will be useful,
--    but WITHOUT ANY WARRANTY; without even the implied warranty of
--    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--    GNU General Public License for more details.
--
--    You should have received a copy of the GNU General Public License
--    along with this program; if not, write to the Free Software
--    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-- Librepos Database upgrade script for PostgreSQL from version 0.0.22 to 0.0.23
-- v0.0.23

UPDATE LIBREPOS SET VERSION = '0.0.23';

ALTER TABLE PEOPLE DROP CONSTRAINT PEOPLE_FK_1;

ALTER TABLE ROLES DROP CONSTRAINT ROLES_PKEY;
ALTER TABLE ROLES ADD COLUMN ID VARCHAR;
UPDATE ROLES SET ID=NAME;
ALTER TABLE ROLES ALTER COLUMN ID SET NOT NULL;
ALTER TABLE ROLES ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX ROLES_NAME_INX ON ROLES(NAME);

ALTER TABLE PEOPLE ADD CONSTRAINT PEOPLE_FK_1 FOREIGN KEY (ROLE) REFERENCES ROLES(ID);

UPDATE ROLES SET PERMISSIONS = $FILE{/net/adrianromero/templates/Role.Administrator.xml} WHERE NAME='Administrator';
UPDATE ROLES SET PERMISSIONS = $FILE{/net/adrianromero/templates/Role.Manager.xml} WHERE NAME='Manager';
UPDATE ROLES SET PERMISSIONS = $FILE{/net/adrianromero/templates/Role.Employee.xml} WHERE NAME='Employee';
UPDATE ROLES SET PERMISSIONS = $FILE{/net/adrianromero/templates/Role.Guest.xml} WHERE NAME='Guest';

ALTER TABLE TICKETS DROP CONSTRAINT TICKETS_FK_2;

ALTER TABLE PEOPLE DROP CONSTRAINT PEOPLE_PKEY;
ALTER TABLE PEOPLE ADD COLUMN ID VARCHAR;
UPDATE PEOPLE SET ID=NAME;
ALTER TABLE PEOPLE ALTER COLUMN ID SET NOT NULL;
ALTER TABLE PEOPLE ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX PEOPLE_NAME_INX ON PEOPLE(NAME);

ALTER TABLE TICKETS ADD CONSTRAINT TICKETS_FK_2 FOREIGN KEY (PERSON) REFERENCES PEOPLE(ID);

ALTER TABLE RESOURCES DROP CONSTRAINT RESOURCES_PKEY;
ALTER TABLE RESOURCES ADD COLUMN ID VARCHAR;
UPDATE RESOURCES SET ID=NAME;
ALTER TABLE RESOURCES ALTER COLUMN ID SET NOT NULL;
ALTER TABLE RESOURCES ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX RESOURCES_NAME_INX ON RESOURCES(NAME);

INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('0', 'Printer.Start', 0, $FILE{/net/adrianromero/templates/Printer.Start.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('1', 'Printer.Ticket', 0, $FILE{/net/adrianromero/templates/Printer.Ticket.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('2', 'Printer.Ticket2', 0, $FILE{/net/adrianromero/templates/Printer.Ticket2.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('3', 'Printer.TicketPreview', 0, $FILE{/net/adrianromero/templates/Printer.TicketPreview.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('4', 'Printer.TicketTotal', 0, $FILE{/net/adrianromero/templates/Printer.TicketTotal.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('5', 'Printer.OpenDrawer', 0, $FILE{/net/adrianromero/templates/Printer.OpenDrawer.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('6', 'Printer.Ticket.Logo', 1, $FILE{/net/adrianromero/templates/Printer.Ticket.Logo.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('7', 'Printer.TicketLine', 0, $FILE{/net/adrianromero/templates/Printer.TicketLine.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('8', 'Printer.CloseCash', 0, $FILE{/net/adrianromero/templates/Printer.CloseCash.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('9', 'Window.Logo', 1, $FILE{/net/adrianromero/templates/Window.Logo.png});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('10', 'Window.Title', 0, $FILE{/net/adrianromero/templates/Window.Title.txt});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('11', 'Ticket.Buttons', 0, $FILE{/net/adrianromero/templates/Ticket.Buttons.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('12', 'Ticket.Line', 0, $FILE{/net/adrianromero/templates/Ticket.Line.xml});
INSERT INTO RESOURCES(ID, NAME, RESTYPE, CONTENT) VALUES('13', 'Printer.Inventory', 0, $FILE{/net/adrianromero/templates/Printer.Inventory.xml});

ALTER TABLE CATEGORIES ALTER COLUMN ID TYPE VARCHAR;

ALTER TABLE TAXES ALTER COLUMN ID TYPE VARCHAR;
CREATE UNIQUE INDEX TAXES_NAME_INX ON TAXES(NAME);

ALTER TABLE PRODUCTS ALTER COLUMN CATEGORY TYPE VARCHAR;
ALTER TABLE PRODUCTS ALTER COLUMN TAX TYPE VARCHAR;

ALTER TABLE LOCATIONS ALTER COLUMN ID TYPE VARCHAR;
CREATE UNIQUE INDEX LOCATIONS_NAME_INX ON LOCATIONS(NAME);

ALTER TABLE STOCKDIARY ALTER COLUMN ID TYPE VARCHAR;
ALTER TABLE STOCKDIARY ALTER COLUMN LOCATION TYPE VARCHAR;
DROP SEQUENCE STOCKDIARYNUM;
ALTER TABLE STOCKCURRENT ALTER COLUMN LOCATION TYPE VARCHAR;

ALTER TABLE CLOSEDCASH ALTER COLUMN MONEY TYPE VARCHAR;
DROP SEQUENCE CLOSEDCASHNUM;

ALTER TABLE TICKETS ALTER COLUMN MONEY TYPE VARCHAR;

ALTER TABLE PRODUCTSOUT ALTER COLUMN TAXID TYPE VARCHAR;

ALTER TABLE PAYMENTS ALTER COLUMN ID TYPE VARCHAR;
DROP SEQUENCE PAYMENTSNUM;

ALTER TABLE FLOORS ALTER COLUMN ID TYPE VARCHAR;
CREATE UNIQUE INDEX FLOORS_NAME_INX ON FLOORS(NAME);

ALTER TABLE PLACES ALTER COLUMN FLOOR TYPE VARCHAR;
ALTER TABLE PLACES ADD COLUMN ID VARCHAR;
UPDATE PLACES SET ID = NAME;
ALTER TABLE PLACES ALTER COLUMN ID SET NOT NULL;
ALTER TABLE PLACES DROP CONSTRAINT PLACES_PKEY;
ALTER TABLE PLACES ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX PLACES_NAME_INX ON PLACES(NAME);

ALTER TABLE RESERVATIONS ALTER COLUMN ID TYPE VARCHAR;
ALTER TABLE RESERVATIONS ADD COLUMN CREATED TIMESTAMP DEFAULT '2001-01-01 00:00:00' NOT NULL;
DROP SEQUENCE RESERVATIONSNUM;

CREATE UNIQUE INDEX THIRDPARTIES_CIF_INX ON THIRDPARTIES(CIF);
CREATE UNIQUE INDEX THIRDPARTIES_NAME_INX ON THIRDPARTIES(NAME);

CREATE TABLE SHAREDTICKETS (
    ID VARCHAR NOT NULL,
    NAME VARCHAR NOT NULL,
    CONTENT BYTEA,
    PRIMARY KEY(ID)
);

