/*
 * JCreditToCard.java
 *
 * Created on 5 de febrero de 2008, 08:16 PM
 */
package org.emar.prepaid.panel;

import net.adrianromero.basic.BasicException;
import net.adrianromero.data.gui.JMessageDialog;
import net.adrianromero.data.gui.MessageInf;
import net.adrianromero.format.Formats;
import net.adrianromero.tpv.forms.AppViewConnection;
import org.emar.prepaid.Tarjeta;

/**
 *
 * @author  Administrator
 */
public class JCreditToCard extends javax.swing.JDialog {

    AppViewConnection m_appcnt;
    private String m_iNumeroTarjeta;
    Tarjeta card;
    

    /** Creates new form JCreditToCard */
    public JCreditToCard() {
        setModal(true);
        initComponents();
        card = null;
        m_appcnt = null;
        m_iNumeroTarjeta = "";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCard = new javax.swing.JTextField();
        jSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jOwner = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBalance = new javax.swing.JTextField();
        jbtnAcreditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setText("ID - Deslice la tarjeta de recarga");

        jCard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCardKeyTyped(evt);
            }
        });

        jSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/adrianromero/images/search.png"))); // NOI18N
        jSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchMouseClicked(evt);
            }
        });

        jLabel2.setText("Dueño");

        jOwner.setEditable(false);

        jLabel3.setText("Saldo Actual");

        jBalance.setEditable(false);

        jbtnAcreditar.setText("Acreditar");
        jbtnAcreditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnAcreditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnAcreditar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBalance)
                            .addComponent(jOwner)
                            .addComponent(jCard, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jbtnAcreditar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void readDataPrepaidCard() {
        if (m_appcnt == null) {
            try {
                m_appcnt = new AppViewConnection();
            } catch (BasicException e) {
                JMessageDialog.showMessage(this, new MessageInf(MessageInf.SGN_DANGER, e.getMessage()));
            }
        }
        this.setM_iNumeroTarjeta(jCard.getText());

        try {
            card = Tarjeta.findId(m_appcnt.getSession(),this.getM_iNumeroTarjeta());
        } catch (BasicException ex) {
            JMessageDialog.showMessage(this, new MessageInf(MessageInf.SGN_DANGER, ex.getMessage()));
        }
        reset();
        if (card != null) {
            jOwner.setText(card.getCliente().getApellido() + " " + card.getCliente().getNombre());
            jBalance.setText(Formats.DOUBLE.formatValue(card.getSaldo()));
        }
    }

    private void reset() {
        jOwner.setText("");
        jBalance.setText("");
    }

    private void jCardKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCardKeyTyped
        if (evt.getKeyChar() == '\n') {
            readDataPrepaidCard();
        }
        else
            reset();
    }//GEN-LAST:event_jCardKeyTyped

    private void jSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchMouseClicked
        readDataPrepaidCard();
}//GEN-LAST:event_jSearchMouseClicked

    private void jbtnAcreditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAcreditarMouseClicked
        setM_iNumeroTarjeta(getCardId());
        this.setVisible(false);
    }//GEN-LAST:event_jbtnAcreditarMouseClicked

    private String getCardId()
    {
        if ( ! "".equals(this.jBalance.getText())  )
            return jCard.getText();
        else
            return "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBalance;
    private javax.swing.JTextField jCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jOwner;
    private javax.swing.JButton jSearch;
    private javax.swing.JButton jbtnAcreditar;
    // End of variables declaration//GEN-END:variables

    public String getM_iNumeroTarjeta() {
        return m_iNumeroTarjeta;
    }

    public void setM_iNumeroTarjeta(String m_iNumeroTarjeta) {
        this.m_iNumeroTarjeta = m_iNumeroTarjeta;
    }
}
