/*
 * JQueryCard.java
 *
 * Created on 5 de febrero de 2008, 09:06 PM
 */

package org.emar.prepaid.panel;

import javax.swing.JComponent;
import net.adrianromero.basic.BasicException;
import net.adrianromero.data.gui.JMessageDialog;
import net.adrianromero.data.gui.MessageInf;
import net.adrianromero.format.Formats;
import net.adrianromero.tpv.forms.AppViewConnection;
import net.adrianromero.tpv.forms.JPanelView;
import net.adrianromero.tpv.forms.AppView;
import net.adrianromero.tpv.forms.UserView;
import org.emar.prepaid.Tarjeta;

/**
 *
 * @author  Administrator
 */
public class JQueryCard extends javax.swing.JPanel implements JPanelView {
    AppViewConnection m_appcnt;
    private String m_iNumeroTarjeta;
    Tarjeta card;
    protected AppView m_App;
    protected UserView m_User;
    /** Creates new form JQueryCard */
    public JQueryCard(AppView oApp, UserView oUser) {
        m_App = oApp;
        m_User = oUser;
        initComponents();
    }

    private void readDataPrepaidCard()
    {
        if (m_appcnt == null) {
            try {
                m_appcnt = new AppViewConnection();
            } catch (BasicException e) {
                JMessageDialog.showMessage(this, new MessageInf(MessageInf.SGN_DANGER,e.getMessage()));
            }
        }
        this.setM_iNumeroTarjeta(jCard.getText());
        
        try {
            card = Tarjeta.findId(m_appcnt.getSession(),this.getM_iNumeroTarjeta());
        } catch (BasicException ex) {
            JMessageDialog.showMessage(this, new MessageInf(MessageInf.SGN_DANGER,ex.getMessage()));
        }
        reset();
        if (card != null)
        {
            jOwner.setText(card.getCliente().getApellido() + " " + card.getCliente().getNombre());
            jBalance.setText(Formats.DOUBLE.formatValue(card.getSaldo()));
            jStatus.setText("A".equals(card.getEstado())?"ACTIVA":"INACTIVA");
        }        

    }
    
    private void reset()
    {
        jOwner.setText("");
        jBalance.setText("");
        jStatus.setText("");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCard = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jOwner = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBalance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jStatus = new javax.swing.JTextField();

        jLabel1.setText("ID Deslice la tarjeta a Consultar");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/adrianromero/images/search.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jCard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCardKeyTyped(evt);
            }
        });

        jLabel2.setText("Dueño");

        jOwner.setEditable(false);

        jLabel3.setText("Saldo");

        jBalance.setEditable(false);

        jLabel4.setText("Estado");

        jStatus.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jBalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jOwner, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jCard, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        readDataPrepaidCard();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jCardKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCardKeyTyped
        if(evt.getKeyChar() == '\n')
            readDataPrepaidCard();
        else
            reset();                
    }//GEN-LAST:event_jCardKeyTyped
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBalance;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jOwner;
    private javax.swing.JTextField jStatus;
    // End of variables declaration//GEN-END:variables

    public String getM_iNumeroTarjeta() {
        return m_iNumeroTarjeta;
    }

    public void setM_iNumeroTarjeta(String m_iNumeroTarjeta) {
        this.m_iNumeroTarjeta = m_iNumeroTarjeta;
    }

    public String getTitle() {
        return "Menu.QueryCard";
    }

    public void activate() throws BasicException {
        
    }

    public boolean deactivate() {
        return true;
    }

    public JComponent getComponent() {
        return this;
    }
    
}
