/*
 * JSearchCard.java
 *
 * Created on 6 de febrero de 2008, 09:47 PM
 */

package org.emar.prepaid.editor;

import net.adrianromero.basic.BasicException;
import net.adrianromero.data.gui.JMessageDialog;
import net.adrianromero.data.gui.MessageInf;
import net.adrianromero.format.Formats;
import net.adrianromero.tpv.forms.AppViewConnection;
import org.emar.prepaid.Tarjeta;

/**
 *
 * @author  Administrator
 */
public class JSearchCard extends javax.swing.JDialog {
    AppViewConnection m_appcnt;
    private String m_iNumeroTarjeta;
    Tarjeta card;
    /** Creates new form JSearchCard */
    public JSearchCard() {
        this.setModal(true);
        initComponents();  
        m_appcnt = null;
        m_iNumeroTarjeta = "";
        card = null;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCard = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBalance = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jOwner = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jStatus = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Deslice la Tarjeta a la que se asignará el saldo");

        jCard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCardKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/adrianromero/images/search.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setText("Saldo");

        jBalance.setEditable(false);

        jLabel3.setText("Dueño");

        jOwner.setEditable(false);

        jLabel4.setText("Estado");

        jStatus.setEditable(false);

        jButton2.setText("OK");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jStatus)
                            .addComponent(jOwner)
                            .addComponent(jBalance)
                            .addComponent(jCard, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
         readDataPrepaidCard();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jCardKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCardKeyTyped
        if(evt.getKeyChar() == '\n')
            readDataPrepaidCard();
        else
            reset();   
    }//GEN-LAST:event_jCardKeyTyped

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if ("I".equals(jStatus.getText()))
        {
            JMessageDialog.showMessage(this, new MessageInf(MessageInf.SGN_DANGER,"No se puede pasar el saldo a una tarjeta inactiva"));
            m_iNumeroTarjeta = "";
        }
        else
        {
            m_iNumeroTarjeta = jCard.getText();
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton2MouseClicked
    
    private void readDataPrepaidCard()
    {
        if (m_appcnt == null) {
            try {
                m_appcnt = new AppViewConnection();
            } catch (BasicException e) {
                JMessageDialog.showMessage(this, new MessageInf(MessageInf.SGN_DANGER,e.getMessage()));
            }
        }
        this.setM_iNumeroTarjeta(jCard.getText());
        
        try {
            card = Tarjeta.findId(m_appcnt.getSession(),this.getM_iNumeroTarjeta());
        } catch (BasicException ex) {
            JMessageDialog.showMessage(this, new MessageInf(MessageInf.SGN_DANGER,ex.getMessage()));
        }
        reset();
        if (card != null)
        {
            jOwner.setText(card.getCliente().getApellido() + " " + card.getCliente().getNombre());
            jBalance.setText(Formats.DOUBLE.formatValue(card.getSaldo()));
            jStatus.setText("A".equals(card.getEstado())?"ACTIVA":"INACTIVA");
        }        

    }
    
    private void reset()
    {
        jOwner.setText("");
        jBalance.setText("");
        jStatus.setText("");
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBalance;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jOwner;
    private javax.swing.JTextField jStatus;
    // End of variables declaration//GEN-END:variables

    public String getM_iNumeroTarjeta() {
        return m_iNumeroTarjeta;
    }

    public void setM_iNumeroTarjeta(String m_iNumeroTarjeta) {
        this.m_iNumeroTarjeta = m_iNumeroTarjeta;
    }
    
}
